spring:
  profiles:
    group: # Run - Edit Configurations - Active Profiles?? ??
      dev: dev
      prod: prod
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

---
spring:
  config:
    activate:
      on-profile: "dev"
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    url: jdbc:mariadb://cccr.cljijk1o7s3n.ap-northeast-2.rds.amazonaws.com/cccr
    username: admin
    password: recipe1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    format_sql: true
  output:
    ansi:
      enabled: always
  security:
    user:
      name: user
      password: 1234
server:
  port: 8080
logging:
  file:
    name: recipe-member
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
jwt:
  token:
    access-expiration-time: 15000
    refresh-expiration-time: 600000
  secretKey: 123nu23n1u23h129312312312
---
---
spring:
  config:
    activate:
      on-profile: "prod"
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    url: jdbc:mariadb://localhost:3306/cccr
    username: root
    password: wu0313127426
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    format_sql: true
  output:
    ansi:
      enabled: always
  security:
    user:
      name: user
      password: 1234
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081
logging:
  level:
    org:hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE

jwt:
  token:
    access-expiration-time: 10000000000
    refreshExpirationTime: 60000
  secretKey: 123nu23n1u23h129312312312
recipe:
  app:
    key: 3929da13f637443a873dd5362af40074


